name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/b39924fc7764c08ae3b51beef9a3518c414cdb7d.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Nix check
        run: nix flake check

      - name: pkgs-hash
        run: nix-shell test/pkgs-hash.nix --command exit

      - name: pkgs-hash with sha
        run: nix-shell test/pkgs-hash.nix --arg with-sha true --command exit

      - name: pkgs-hash with system
        run: nix-shell test/pkgs-hash.nix --arg with-system true --command exit

      - name: pkgs-flake
        run: nix-shell test/pkgs-flake.nix --command exit

      - name: pkgs-flake with system
        run: nix-shell test/pkgs-flake.nix --arg with-system true --command exit

      - name: pkgs-hash-or-flake hash
        run: nix-shell test/pkgs-hash-or-flake.nix --command exit

      - name: pkgs-hash-or-flake hash with sha
        run: nix-shell test/pkgs-hash-or-flake.nix --arg with-sha true --command exit

      - name: pkgs-hash-or-flake hash with system
        run: nix-shell test/pkgs-hash-or-flake.nix --arg with-system true --command exit

      - name: pkgs-hash-or-flake flake
        run: nix-shell test/pkgs-hash-or-flake.nix --arg use-hash false --command exit

      - name: pkgs-hash-or-flake flake with system
        run: nix-shell test/pkgs-hash-or-flake.nix --arg use-hash false --arg with-system true --command exit

      - name: Formatting
        run: nix run github:tbidne/nix-hs-tools/0.6.1#nixpkgs-fmt -- --check
